/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _PraticaGradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertFalse(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'false'");
    }
}
